#version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU

init:
  # Set "build version number" to "short-commit-hash" or when tagged to "tag name" (Travis style)
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
      }
      else
      {
        Update-AppveyorBuild -Version "dev-$($env:APPVEYOR_REPO_COMMIT.substring(0,7))"
      }

install:
    git submodule update --init --recursive

before_build:
- ps: >-
    nuget.exe restore CoinbasePro.Application.sln

build:
  project: CoinbasePro.Application.sln
  verbosity: normal

test:
  assemblies:
    only:
    - '**\*.Test.dll'